[package]
name = "simpath"
version = "1.3.0"
authors = ["Andrew Mackenzie <andrew@mackenzie-serres.net>"]
description = "Search for files on a path defined in an environment variable"
license = "MIT"
documentation = "https://github.com/andrewdavidmackenzie/simpath/README.md"
homepage = "https://github.com/andrewdavidmackenzie/simpath/README.md"
repository = "https://github.com/andrewdavidmackenzie/simpath/"
readme = "README.md"